import nodemailer from 'nodemailer';
import Mailgen from 'mailgen';

import dotenv from 'dotenv';
dotenv.config();

export const registerMail = async (req, res) => {
    const { username, userEmail, text, subject } = req.body;

    let Config = {
        service:'gmail',
        auth: {
            user: process.env.EMAIL, // generated by gmail user
            pass: process.env.PASSWORD, // generated by gmail password
        }
    }
    
    let transporter = nodemailer.createTransport(Config);
    
    let MailGenerator = new Mailgen({
        theme: "default",
        product : {
            name: "Mailgen",
            link: 'https://mailgen.js/'
        }
    })

    // body of the email
    var response = {
        body : {
            name: username,
            intro : text || 'registered your mail',
            outro: 'Need help, or have questions? Just reply to this email, we\'d love to help.'
        }
    }

    var emailBody = MailGenerator.generate(response);

    let message = {
        from : process.env.EMAIL,
        to: userEmail,
        subject : subject || "Signup Successful",
        html : emailBody
    }

    // send mail
    transporter.sendMail(message)
        .then(() => {
            return res.status(201).send({ msg: "You should receive an email from us."})
        })
        .catch(error => res.status(500).send({ error }))

}